apiVersion: v1
description: Plex Media Server
name: kube-plex
version: 0.3.2
keywords:
  - plex
home: https://plex.tv/
icon: https://www.plex.tv/wp-content/uploads/2018/01/pmp-icon-1.png
sources:
  - https://github.com/ressu/kube-plex
  - https://hub.docker.com/r/plexinc/pms-docker/
maintainers:
  - name: Sami Haahtinen
    email: ressu@ressukka.net
