apiVersion: v1
appVersion: 1.10.1.4602-f54242b6b
description: Plex Media Server
name: kube-plex
version: 0.2.0
keywords:
  - plex
home: https://plex.tv/
icon: https://www.plex.tv/wp-content/uploads/2018/01/pmp-icon-1.png
sources:
  - https://github.com/munnerz/kube-plex
  - https://hub.docker.com/r/plexinc/pms-docker/
maintainers:
  - name: munnerz
